// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

/// GatewayControl is the control plane API for Connect Gateway.
///
/// @Snippet(path: "GatewayControlQuickstart")
public class GatewayControlClient: Clients.GatewayControlProtocol {
  let inner: any Clients.GatewayControlStub

  /// Creates a new `GatewayControlClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.GatewayControlStub = try Clients.GatewayControlTransport(options)
    inner = Clients.GatewayControlRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.GatewayControlLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// GenerateCredentials provides connection information that allows a user to
  /// access the specified membership using Connect Gateway.
  ///
  /// @Snippet(path: "GatewayControl_GenerateCredentials")
  public func generateCredentials(
    request: GenerateCredentialsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEConnectGatewayV1.GenerateCredentialsResponse {
    try await self.inner.generateCredentials(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `GatewayControlClient`.
  ///
  /// To mock `GatewayControlClient` change your functions to receive
  /// `some GatewayControlProtocol` or `any GatewayControlProtocol`
  /// and pass a mock implementation in your tests.
  public protocol GatewayControlProtocol {
    /// See `GatewayControlClient.generateCredentials`.
    func generateCredentials(request: GenerateCredentialsRequest) async throws
      -> GoogleCloudGKEConnectGatewayV1.GenerateCredentialsResponse

    /// See `GatewayControlClient.generateCredentials`.
    func generateCredentials(
      request: GenerateCredentialsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEConnectGatewayV1.GenerateCredentialsResponse
  }
}

// Default implementations
extension Clients.GatewayControlProtocol {
  public func generateCredentials(request: GenerateCredentialsRequest) async throws
    -> GoogleCloudGKEConnectGatewayV1.GenerateCredentialsResponse
  {
    try await self.generateCredentials(request: request, options: .init())
  }

  public func generateCredentials(
    request: GenerateCredentialsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEConnectGatewayV1.GenerateCredentialsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
