// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// A request for connection information for a particular membership.
public struct GenerateCredentialsRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The Fleet membership resource.
  public var name: Swift.String = Swift.String()

  /// Optional. Whether to force the use of Connect Agent-based transport.
  ///
  /// This will return a configuration that uses Connect Agent as the underlying
  /// transport mechanism for cluster types that would otherwise have used a
  /// different transport. Requires that Connect Agent be installed on the
  /// cluster. Setting this field to false is equivalent to not setting it.
  public var forceUseAgent: Swift.Bool = Swift.Bool()

  /// Optional. The Connect Gateway version to be used in the resulting
  /// configuration.
  ///
  /// Leave this field blank to let the server choose the version (recommended).
  public var version: Swift.String = Swift.String()

  /// Optional. The namespace to use in the kubeconfig context.
  ///
  /// If this field is specified, the server will set the `namespace` field in
  /// kubeconfig context. If not specified, the `namespace` field is omitted.
  public var kubernetesNamespace: Swift.String = Swift.String()

  /// Optional. The operating system where the kubeconfig will be used.
  public var operatingSystem: GenerateCredentialsRequest.OperatingSystem =
    GenerateCredentialsRequest.OperatingSystem()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `GenerateCredentialsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GenerateCredentialsRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let forceUseAgent = CodingKeys(stringValue: "forceUseAgent")
    static let version = CodingKeys(stringValue: "version")
    static let kubernetesNamespace = CodingKeys(stringValue: "kubernetesNamespace")
    static let operatingSystem = CodingKeys(stringValue: "operatingSystem")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "forceUseAgent",
      "version",
      "kubernetesNamespace",
      "operatingSystem",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .forceUseAgent) {
      self.forceUseAgent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .version) {
      self.version = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kubernetesNamespace) {
      self.kubernetesNamespace = value
    }
    if let value = try container.decodeIfPresent(
      GenerateCredentialsRequest.OperatingSystem.self, forKey: .operatingSystem)
    {
      self.operatingSystem = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.forceUseAgent, forKey: .forceUseAgent)
    try container.encode(self.version, forKey: .version)
    try container.encode(self.kubernetesNamespace, forKey: .kubernetesNamespace)
    try container.encode(self.operatingSystem, forKey: .operatingSystem)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Operating systems requiring specialized kubeconfigs.
  public enum OperatingSystem: Codable, Equatable, Sendable {
    /// Generates a kubeconfig that works for all operating systems not defined
    /// below.
    case unspecified
    /// Generates a kubeconfig that is specifically designed to work with
    /// Windows.
    case windows
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .windows: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "OPERATING_SYSTEM_UNSPECIFIED"
      case .windows: return "OPERATING_SYSTEM_WINDOWS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:OperatingSystem/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "OPERATING_SYSTEM_UNSPECIFIED": self = .unspecified
      case "OPERATING_SYSTEM_WINDOWS": self = .windows
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:OperatingSystem/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .windows
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("OPERATING_SYSTEM_UNSPECIFIED")
      case .windows: return try container.encode("OPERATING_SYSTEM_WINDOWS")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkeconnect.gateway.v1.GenerateCredentialsRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
